apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: gcr.io/searce-playground-v1/cicd-python:420b7c7b8dcd726e61b1b7044bafd8ddc786fde7
          ImagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000

