apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python
  name: python   
spec:
  replicas: 0
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: gcr.io/searce-playground-v1/cicd-python:d650ccd3c29c77b56ec20da863c54c1084714acc
          ImagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000

